### ISSUE TITLE
Highlight operators

### ISSUE THREAD

**Issue by Gameghostify** [demenskiy/mokka#1]
This theme is awesome, but I feel like operators should be highlighted some more

For example, the difference between these two is not really apparent at first sight (to me)
![image](https://user-images.githubusercontent.com/33099493/119387520-5b3b6680-bcc9-11eb-8ce4-2b0160e3c76c.png)

Something like this seems much better to me, but I realize it might be too bright (considering that the theme is made to _not_ have a lot of highlighting)
![image](https://user-images.githubusercontent.com/33099493/119388365-79559680-bcca-11eb-96bb-0ae7989f68ee.png)

**Comment by demenskyi** [comment]
Thank you for your feedback and suggestion! But writing code, I don't want pay special attention to operators, braces and "semantic" stuff.
You can override these colors in settings if you need it. Thanks!
